spring.application.name=ApiGateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=ProductService
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ProductService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

spring.cloud.gateway.server.webmvc.routes[1].id=CategoryService
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CategoryService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/categories/**

jwt.secret= ThisIsAVeryLongSecretKeyForJwtAuthenticationSpringBootMicroservices123456
jwt.expiration=3600000


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
